### ISSUE TITLE
[input-history] Strange behaviour when using modifier keys

### ISSUE THREAD

**Issue by Viginox** [univrsal/input-overlay#122]
**Describe the bug**
When using key combinations like `Shift + D` or similar ones, the behaviour is sometimes very strange.

When you press those very fast and release them, sometimes the pressed key (in this case `D`) will only show up for a very short time and is then deleted immediately that only the modifier remains on screen

Another thing: When `Enable auto clear` is ticked, this will also delete the modifier key when it is held down after some time. So when you hold down the modifier for longer than the set time, it won't be displayed anymore when you press another key.

**To Reproduce**
* Load default settings
* Hold down a modifier key (i.e. `shift`)
* Tap the `D` key and release it.
* Repeat that a few times but make sure to just tap it like you would type a capital letter when writing
--> Now the `D` key should only show up very briefly
* When you hold down the `D` key for about a second, it will be displayed correctly

**Expected behavior**
The writing `Shift + D` should stay on screen until the next key press or mouse action occurs.

**Additional information:**
- Plugin version
     - v4.8-3
- Full OBS Studio write_log
    - No info in log files because no software bug

**Comment by LagrangeVI** [comment]
I figured this might be related here instead of creating new issue. 

When you press and hold key combinations of 3 or more (repeated keys enabled) then let go any key that is not first or last in the sequence, only the key/s pressed and held before it gets retained and the rest are gone.

For example `Shift` + `E` + `R` + `Left Mouse` if I let go of `E`, the `R` and `Left Mouse` is gone too.

**Comment by univrsal** [comment]
Input history will be removed from the plugin and readded through the browser source, so I'll close this.
