### ISSUE TITLE
Input-History: Crash after 6 hour streaming

### ISSUE THREAD

**Issue by CHEF-KOCH** [univrsal/input-overlay#13]
Damn I really got _salty_, sorry to say but I was streaming 6 hours and almost finished the game, then suddenly obs64 froze and crashed. I restarted OBS64 and after 5 minutes it happened again, so I was forced to disable the overlays and the cpu got down around 2% and the stream got stabilized.

[New Text Document (6).txt](https://github.com/univrsal/input-overlay/files/1583693/New.Text.Document.6.txt)
[New Text Document (7).txt](https://github.com/univrsal/input-overlay/files/1583692/New.Text.Document.7.txt)

Hopefully the cpu usage and the bug can be fixed. I'm unsure what is causing it exactly cause I did not something special.

**Comment by univrsal** [comment]
Hmm the problem is that I can not make any sense of OBS crash logs since they only show memory addresses, which don't tell me anything.
I guess you were using the input history source, any specific settings? 
I noticed some other issues with input history so I guess I'll have to revise some things anyways

**Comment by CHEF-KOCH** [comment]
I close the issue since I was unable to reproduce the crash and v3 with Unicode support seems to be more stable.
