### ISSUE TITLE
[Suggestion] Possibility of replacing keys with icons/custom text in history

### ISSUE THREAD

**Issue by Kiloutre** [univrsal/input-overlay#19]
![sf](https://user-images.githubusercontent.com/11745692/35322875-0ad4e3c0-00ec-11e8-807a-06c71547441b.gif)

Hey man, i've been using your plugin to make myself a basic street fighter overlay, but there's stuff that i'd like to do regarding the history that i can't at the moment.
The problem is that the history shows which keys are used when in street fighter (and various games), each specific command has a name and that name is used by the community (e.g. a Light-Punch on my keyboard is Q, however it's name should be LP, and on an american keyboard it should be A). So i'd like to be able to attribute images to keys, or at the very least custom names, so that the history matches the input overlay

Being able to only allow specific keys to show up in the history would also be pretty neat, because if i stream with the history i can't afford to type any password even though i only have the history on for 6 specific keys. Would also be neat to be able to show the history fully horizontally, in order to show combos properly

Also, the names of arrow keys is messed up (it shows their value instead), i don't know why

**Comment by univrsal** [comment]
To implement that I'd probably add a config file that allows to rename keys and add an option to only display keys that are defined in the file.
As for the horizontal display: Would you want the keys to be chained into one line of text with, for example a space to separate them?
Also replacing keys with icons would be more difficult, because I currently only use a text source to draw the input history but I think I could pull it off, although it would mean that all keys need to have their own icon because a mixture of icons and texts would get pretty complicated.
Lastly the arrow keys are displayed as hex codes because I forgot to give them a name :P 

So yeah I'll give this a shot but I'll probably have to put it off until Friday or at least tomorrow

**Comment by univrsal** [comment]
Small update:
Renaming keys is up and working, icons will still take a little while since I'm also working on showing mouse movement which is proving to be a little tricky.
![unbenddannt](https://user-images.githubusercontent.com/8353672/35477362-15c44532-03c1-11e8-97a0-0892d564eda5.png)

**Comment by univrsal** [comment]
Alrighty, so this was more work than I originally anticipated but it's done:
![gif](https://user-images.githubusercontent.com/8353672/35700077-3dacba8c-0792-11e8-8a17-ad030b3e3a01.gif)
Give me a little more time and I'll make a new release

**Comment by Kiloutre** [comment]
Thank you for the work! That's pretty neat
