### ISSUE TITLE
Feature request: show only the key currently being pressed

### ISSUE THREAD

**Issue by lf-** [univrsal/input-overlay#2]
It would be nice (though potentially out of scope) to have a list of inputs that automatically scrolls and fades out after a certain number of seconds following the keystroke. For example, I press A, then S. It shows A, then pushes up the A, then shows the S, then the A fades out, then the S.

This would be the ideal situation for doing tutorials without wasting screen space on showing the entire keyboard (and also preventing people from missing quick keystrokes). Of course, I could probably use one of the many applications that already do this, but it would be perfect if it was directly integrated into my recording software so I can set it and forget it as well as not having it block my view.

**Comment by univrsal** [comment]
I already thought about having something like this, but I orignally intended this to be used for gaming so I'm not sure if I'll add this.
I'd like to get linux support first and then maybe look into this.

**Comment by univrsal** [comment]
Little heads up on the situation (I haven't forgotten, yet :P).
I'm working on this again and making some progress:

![unbenannt](https://user-images.githubusercontent.com/8353672/33573845-6fd448ce-d937-11e7-93cf-25d2c04aa4ea.png)

As you can see it's still pretty rough around the edges, but since I got this far I'm positive I can implement the feature

**Comment by univrsal** [comment]
Alrighty, the first version is finished and I'd like to hear some feedback if you're up for testing it out.
