### ISSUE TITLE
Mouse movement stopped.

### ISSUE THREAD

**Issue by Psychodeus** [univrsal/input-overlay#207]
As you can see here, mouse movement stop when I click RMB or LMB, and perhaps other button from mouse too will trigger this.

![ezgif-7-576aae8b910d](https://user-images.githubusercontent.com/93028949/138546769-82a51331-169e-417b-871d-a7d1c03e4653.gif)

**Comment by spartanatreyu** [comment]
Yeah, I have the same issue

**Comment by spartanatreyu** [comment]
I'm unfamiliar with this codebase and haven't touched C++ since before C++11, but it looks like there are a few `switch` `case` statements relating to mouse events that have early exits (`break` / `return` statements).

Maybe the cases need to ["fall through"](https://github.com/kwhat/libuiohook/blob/fa7d67713c5c53180e8a1825ba794595b33c050b/demo/demo_hook.c#L105-L114) to allow simultaneous events to be passed through

**Comment by acewins727** [comment]
I have the same issue and tried fixing it and now it doesn't move at all

**Comment by univrsal** [comment]
I just tested this and this should be fixed with the next release.
