### ISSUE TITLE
Websocket forwarding does not get filtered

### ISSUE THREAD

**Issue by konahart** [univrsal/input-overlay#236]
**Description**
While inputs can be filtered using the whitelist/blacklist method with a standard Input Overlay, "forward events through websocket server" sends *all* inputs. Since the window origin is not included in the data sent to the websocket, this makes it impossible to filter if using the input-history workaround.

Not a "bug" per se, but does not seem like an unintended behavior.

**To Reproduce**

1. Check "forward events through websocket server" option
2. Add a window title to filter
3. Open input-history-windows or [websocket example](https://github.com/univrsal/input-overlay/blob/master/projects/plugin/data/example.html), and inputs that should be filtered are displayed

**Expected behavior**
Input events from filtered windows should not be sent to the websocket
(there is an 'event_source' in the data, but it only shows 'local' or 'network')

**Additional information:**
- Plugin version: pre-release 5.0

**Comment by grillo-delmal** [comment]
Just to ping, this issue is still present on version 5.0

This might not be a fix, but I made this OBS script to deal with this issue for now.

https://gist.github.com/grillo-delmal/b23d6528e2d05ddfe0c9afc39d2679cb

Is not a perfect solution, but I'll go with this until the issue is actually solved :)
