### ISSUE TITLE
Weird conflicts with Alt-Drag

### ISSUE THREAD

**Issue by Scrxtchy** [univrsal/input-overlay#34]
### What happened:

When uiohook.dll is loaded into OBS and [altdrag](https://stefansundin.github.io/altdrag/) is running on the system
when using the alt key and dragging to move windows on the system, alt-drag does not detect that the mouse key has been let go. Instead the user must click to let go of the window

### What was supposed to happen:

application should not conflict, this can be tested by; 
letting go of MB1, the window should stop moving with the cursor

**Comment by kaimi** [comment]
Wow, another AltDrag user :D

Can confirm, AltDrag 1.1 / fully updated Windows 10 Pro. Input Overlay 4.5.

**Comment by univrsal** [comment]
I don't have access to a windows machine right now and I'll be busy with exams for the near future, so I can't guarantee anything for now.
Also this is either an issue with uiohook or altdrag, so I can't really do anything since I have no control over either of those.

**Comment by Scrxtchy** [comment]
Best that could be done if it was a uiohook issue would be to upstream it
altdrag development is actually dead but any advice among any developers could lead to a solution

**Comment by univrsal** [comment]
libuiohook hasn't been worked on for quite some time as well, so yeah this might get complicated.
I don't know if it'll help but maybe @kwhat can chime in.

**Comment by kwhat** [comment]
If you are using the master branch, it is indeed broken with some changes I was playing with for 2.0.  Please make sure you are using the 1.1 branch.  There are some known issues with dead keys, but the bulk of it should be working. 

As far as this Alt-Drag program, I am not sure why it is misbehaving. The uiohook library should only be doing passive hooks by default and does not change the state of any of the keys on the system.  The only  thing I can think of is that the uiohook is being used, but the user is blocking the dispatch thread which could interfere with other applications using SetWindowsHookEx.  When you setup a hook with this callback, it must return as quickly as possible.  If you do not need to modify the system events, you should copy the memory of the event, and dispatch that copy into your programs main threads memory.  The hook callback for this library is pretty low level and will block if you block the system.  This could be what is preventing the release in the Alt-Drag program.  I cannot tell for sure without the source for a use case that causes this behavior with Alt-Drag.  If you are using one of the sample programs, you should be using the one with threads.

**Comment by univrsal** [comment]
Thanks for the answer! I think I used the 1.1 release when I compiled uiohook but I'll double check.
I reused most of the code from [demo_hook_async.c](https://github.com/kwhat/libuiohook/blob/1.1/src/demo_hook_async.c) and only added a few things to the [proccess_event](https://github.com/univrsal/input-overlay/blob/master/hook/hook-helper.cpp#L257) method so OBS has an array of currently pressed keys.

Other than that I have to admit that I do not know much about how the input hooks work so I don't think that we'll find a solution here since I don't want to bother kwhat too much.

I did dig a little, though and looked at how AltDrag registers its hook and the only thing that I can say is that it looks a little different compared to how uiohook does it (and how I remember reading about it on msdn):

from [altdrag.c](https://github.com/stefansundin/altdrag/blob/master/altdrag.c#L209):
```
  // Load keyboard hook
  HOOKPROC procaddr;
  if (!keyhook) {
    // Get address to keyboard hook (beware name mangling)
    procaddr = (HOOKPROC) GetProcAddress(hinstDLL, "LowLevelKeyboardProc@12");
    if (procaddr == NULL) {
      Error(L"GetProcAddress('LowLevelKeyboardProc@12')", L"This probably means that the file hooks.dll is from an old version or corrupt. You can try reinstalling "APP_NAME".", GetLastError());
      return 1;
    }
    // Set up the keyboard hook
    keyhook = SetWindowsHookEx(WH_KEYBOARD_LL, procaddr, hinstDLL, 0);
    if (keyhook == NULL) {
      Error(L"SetWindowsHookEx(WH_KEYBOARD_LL)", L"Could not hook keyboard. Another program might be interfering.", GetLastError());
      return 1;
    }
  }
```
So uhh yeah I'm kinda out of ideas so the last one I could ask is @stefansundin but otherwise I'm clueless since I switched to uiohook to avoid having to deal with the hook stuff and Xorg.

**Comment by kwhat** [comment]
> Other than that I have to admit that I do not know much about how the input hooks work.
Don't feel bad, no one does... There is a TON of hook magic going on behind the scenes that microsoft has not documented, including blocking the hook can disable the hook and all kinds of other undefined behavior. 

I can tell you what the uiohook lib does by not why it doesn't work with Alt-Drag. I did take a look at the Alt-Drag source and didn't see anything unusual.

So, when the hook calls back to your library its calling back on the SetWindowsHookEx proc_addr context of the Windows OS.  For non-consuming event workloads, the memory for the event is copied to another thread and queued for delivery by some kind of worker pattern.  If you need to consume the events, you must all work on the callbacks context and set the reserved flag to 0x01.  This context switching is important because the return of the proc_addr is very time sensitive as it will block the delivery of events to other applications until you return.  This blocking could be an issue in either library, but if you are using the Threaded example, you are probably not blocking as far as uiohook goes, but IDK if there is something in Alt-Drag that maybe blocking or doing something wired with its callbacks.  There could also be an issue with the dll used by Alt-Drag conflicting with the uiohook library.  The dll for each application should its own.  Does Alt-Drag use a dll for hooking because that maybe the issue.  You are not supposed to use WH_KEYBOARD_LL or WH_MOUSE_LL from outside a DLL nor should to callback be registered outside a DLL.  This could be why Alt-Drag exhibits strange behavior.

**Comment by kwhat** [comment]
So I just remembered that I had to do some really strange stuff on windows to make the hook keep working with a very particular type of application.  For some undocumented reason, Windows loses event hooks when the user transfers to a vmware or rdp.  In order to work around this problem I added the following callback [src/windows/input_hook.c#L630](https://github.com/kwhat/libuiohook/blob/1.1/src/windows/input_hook.c#L630) which attempts to renegotiate the hook and resume events.  This piece maybe where there is in issue in uiohook.  

Set the log level to debug, and see if you get anything interesting printed out or patch out the call [here](https://github.com/kwhat/libuiohook/blob/1.1/src/windows/input_hook.c#L699) and see if it works.

**Comment by univrsal** [comment]
Yeah I'll do that and see if I find anything

**Comment by Scrxtchy** [comment]
I'd like to give an update to this issue after 2 years.

The issue in the OP is no longer accurate, input-overlay no longer has a negative effect when I use AltDrag.
The plugin works at about 99% effectiveness, the only issue is that now input-overlay now does not detect the button being let go (reversing the statement in the OP). However, it still continues to operate as normal, resetting to a normal display the next the key is pressed.
This isn't even a nuisance in my eyes, as I expect at least some incompatibility. 
But as the plugin no longer has a negative effect on AltDrag (and the workflow of it's users), I will happily mark this issue as resolved.
Thank you for continuing to maintain this plugin

**Comment by univrsal** [comment]
I don't really know whats causing keys getting stuck, but it might be that either input overlay or libuiohook doesn't receive the key up event.

**Comment by kwhat** [comment]
So, when the hook renegotiates some event data maybe "lost" while that happens.  It could manifest in a bunch of different ways for different people.  I would suggest looking at the debug level logs to see if that is what is happening.  Definitely open an issue upstream with uiohook and ill take a look at some point.
