### ISSUE TITLE
Is it a malware?

### ISSUE THREAD

**Issue by Davimineboy7862** [univrsal/input-overlay#418]
Good morning guys, today I got a warning of Windows, and when I putted it on the virustotal, it said that had 2 antivirus scanned and found malware...

**Describe the bug**
It's just the warning from Windows and scan from virus total...

**To Reproduce**
Download the Windows version of the instaler, maybe will appear...

**Expected behavior**
I thought that was going to install the input overlay, because I started today with OBS Studio...

**Screenshots**
![image](https://github.com/user-attachments/assets/8e24a9ca-3d66-4d96-93bc-83abfb35ce34)
![image](https://github.com/user-attachments/assets/566b4e0d-d16b-437b-b619-3fabffb8edf2)

**Additional information:**
The lastest version...
[2024-09-30 11-26-41.txt](https://github.com/user-attachments/files/17191725/2024-09-30.11-26-41.txt)

**Additional context**
Nah, I pass...

**Comment by univrsal** [comment]
The windows warning is only there because the executable is unsigned. Digitally signing an installer requires a certificate which I don't have. Two false positives out of 73 scans should make it pretty clear that the plugin does not contain any malware, provided you downloaded it from the official release page.

**Comment by Davimineboy7862** [comment]
Oh, sorry, then...
