### ISSUE TITLE
Keys with no "up" state

### ISSUE THREAD

**Issue by patcolyn** [univrsal/input-overlay#44]
**Describe the bug**
When using a key with no natural up/down state (eg. scroll) the overlay does not display/update as expected.

**To Reproduce**

No input:
1. Input scroll
2. Do not provide input
3. Overlay keeps scroll highlighted until input is provided

Constant Input:
1. Provide high number of inputs (move cursor) for duration
2. scroll
3. Overlay only shows input for one frame, not visible

**Expected behavior**
Mouse overlay shows scroll inputs visibly

**Screenshots**
![image](https://user-images.githubusercontent.com/13235826/42723846-4c3c3cbc-8767-11e8-91c1-144f33c54224.png)

**Additional information:**
- Plugin version: v4.7
- Full OBS Studio log: [2018-07-14 12-39-37.txt](https://github.com/univrsal/input-overlay/files/2194897/2018-07-14.12-39-37.txt)

**Comment by univrsal** [comment]
I am aware of this bug. This is because of how the input library works.
It only sends a event when the users is scrolling but it doesn't send one when the user stops scrolling, which means I disable scrolling everytime any type of event is sent (eg. Mouse movement) and enable scrolling when the scrolling event is set, which results in the flickering scroll texture when you move your mouse and scroll at the same time.

As of now I have not found a way to prevent this from happening, but I'm open to suggestions

**Comment by patcolyn** [comment]
I looked through the source and the way you implemented it is likely the most sensible one, though can cause issues with high polling rate mice.

I guess a usability alternative would be to highlight the texture for a set duration, say 25ms as an example. Refresh the 25ms highlight timer every event for continuously scrolling. Would give similar feedback to a single click, but this solution would not communicate a specific number of events.

**Comment by univrsal** [comment]
We'll seem, maybe I can come up with a solution at some point

**Comment by univrsal** [comment]
Just a little heads up, I added a timer which will reset the scrolling after 120ms of no scrolling event.
It'll be in 5.0, once it's ready
