### ISSUE TITLE
Minimal History not working correctly

### ISSUE THREAD

**Issue by MoXAriApph** [univrsal/input-overlay#50]
**Describe the bug**
Minimal History will not display anything

**To Reproduce**
Install Input Overlay (4.7.2) normally and add an Input Overlay to OBS (Minimal Input History)

**Expected behavior**
It should work correctly and display keys when pressed

**Screenshots**
![snag-4627](https://user-images.githubusercontent.com/20781130/44948422-a9560080-ade2-11e8-84b8-2fe6612291cc.png)
![snag-4628](https://user-images.githubusercontent.com/20781130/44948424-b377ff00-ade2-11e8-8ba4-aed60d4cd5d3.png)
![snag-4629](https://user-images.githubusercontent.com/20781130/44948427-b7a41c80-ade2-11e8-8333-faeeaac879b2.png)
![snag-4630](https://user-images.githubusercontent.com/20781130/44948428-b96de000-ade2-11e8-930a-f28d5cf8c554.png)

**Additional information:**
- Plugin version: 4.7.2
- https://pastebin.com/kGznww2w

**Additional context**
This seems to be the only overlay that isn't working, everything else works :L

**Comment by univrsal** [comment]
That is a preset for input-history:

![image](https://user-images.githubusercontent.com/8353672/44949025-5489a880-ae29-11e8-8812-59524b9c4d04.png)

**Comment by MoXAriApph** [comment]
Input history doesn't let me change overlay modes? 🤔 
![snag-4637](https://user-images.githubusercontent.com/20781130/44949499-7b7bb680-adf8-11e8-9924-05d844ddc34e.png)

**Comment by univrsal** [comment]
Have you tried looking for the option further down? Also try updating obs as well as deleting and recreating an input-history source

**Comment by MoXAriApph** [comment]
Updated OBS, nothing changed, also deleted and re-added the plugin, no change either
![record 90](https://user-images.githubusercontent.com/20781130/44949685-3e192800-adfc-11e8-9c2e-c792ce60d0cf.gif)

newest log file 
[2018-09-01 15-27-16.txt](https://github.com/univrsal/input-overlay/files/2342748/2018-09-01.15-27-16.txt)

**Comment by univrsal** [comment]
can you try replicating this in an empty scene collection? I'm a little confused as to why only one option would be missing

**Comment by univrsal** [comment]
the stuff I fabricate never ceases to amaze me, guess I'll try looking into the old code.
One last thing: can you give me the *.json file of that scene collection? It should be under
```
"%appdata%\obs-studio\basic\scenes\test bruh.json"
```

**Comment by MoXAriApph** [comment]
[test_bruh.zip](https://github.com/univrsal/input-overlay/files/2342824/test_bruh.zip)

**Comment by univrsal** [comment]
Welp I'm still clueless but I'll try my best

**Comment by univrsal** [comment]
Okay I added a small debug line to see if the listbox gets even added. Can you try the attached *.dll *put it in the 64bit plugin directory, usually under C:\Program Files (x86)\obs-studio\obs-plugins\64bit) and post the log again?
[input-overlay.zip](https://github.com/univrsal/input-overlay/files/2343620/input-overlay.zip)

**Comment by MoXAriApph** [comment]
Newest log
[2018-09-02 16-02-37.txt](https://github.com/univrsal/input-overlay/files/2343748/2018-09-02.16-02-37.txt)

**Comment by univrsal** [comment]
Crap I forgot to ask you to open the properties of any input-history source, but in the log it says that you added a input-history to the scene "Clone Hero" so I assume you saw the properties window and verified that the combobox wasn't there?
Because in the log I also can not see the line "ADDED HISTORY MODE LIST" which should be written, when the properties window is opened.

Looking at the gif you posted earlier, I'm guessing that you're running an older version (because the properties do not match mine at all) of input-overlay and somehow are installing the new ones incorrectly.
Can you verify that obs studio is loading the new dll? Did you maybe install obs twice in different locations?
[input-overlay.zip](https://github.com/univrsal/input-overlay/files/2343773/input-overlay.zip)
You can try the attached build and give me another log, but other than this I don't really have an answer for this

**Comment by MoXAriApph** [comment]
Nevermind, kms, what is this
I was being an idiot and just dropped the **Literal** plugin folder into there rather than the contents of the folder
_C:\Program Files (x86)\obs-studio\plugin_

It works now

**Comment by univrsal** [comment]
yeah I figured, guess this mystery is solved
