### ISSUE TITLE
Alpha with filtering

### ISSUE THREAD

**Issue by Voxelse** [univrsal/input-overlay#61]
Hey!

I don't really know if it's a bug on your side or a OBS one but here is my problem:
I made a layout for my controller and at first, it looks good except that it's pretty blurry due to the low resolution of my texture.
But when I try to put a point filter (or any of the other filters) the alpha is not working correctly anymore (probably some layering issues)

You can reproduce this by putting multiple buttons on top of each with alpha

I would expect layered buttons to not be overwritten by alpha

![input_overlay_alpha](https://user-images.githubusercontent.com/11724596/47711272-2233d600-dc35-11e8-8ffe-83ea568373f6.png)

- Plugin version : 5.0 (the one you gave on the switch controller issue : https://github.com/univrsal/input-overlay/issues/55)
- Full OBS Studio log : [2018-10-30 11-17-05.txt](https://github.com/univrsal/input-overlay/files/2529137/2018-10-30.11-17-05.txt)

Thanks!

P.S: I'm using the 5.0 version because I didn't manage to make separate textures for Dpad buttons on the current release and because the io-cct tool is amazing

**Comment by univrsal** [comment]
Yeah that's something I haven't figured out yet. Applying any kind of filtering (scaling or separate filters) will result in weird cropping issues.
It's something I'll have to ask the obs developers about since I don't know what's causing it. I don't know when I'll be able to fix that, but until then you could try and scale your overlay texture by a whole number and use "nearest neighbor" for filtering (depending on what software you use it might be different).

Glad you like the config tool though

**Comment by Voxelse** [comment]
Ok. I thought about upscaling the texture but just wanted to know if you had an easy fix for that since it requires to modify the layout and the texture a bit but that's definitively not a big deal.
And thanks for the really quick reply!

**Comment by univrsal** [comment]
I know this issue is a tad old, but it seems this was an issue with obs studio, so it should be fixed now. If not I'll reopen this.
